#pragma once

#include <string>
#include <cinder/TriMesh.h>

struct ObjectLoader
{
	ObjectLoader() = delete;

	/**
	Loads .obj-files generated by the bullet-simulation or by the preprocessor.
	Supports:
	 - Position
	 - Vertex Normal
	 - Vertex Color
	 - Cell indices, stored in TexCoord1
	*/
	static ci::TriMeshRef loadCustomObj(const std::string& path);

	static void saveCustomObj(ci::TriMeshRef mesh, const std::string& path);

	/**
	Saves binary .ply-files.
	Supports position, normal, vertex color, TexCoord0, TexCoord1
	*/
	static void saveMeshPly(ci::TriMeshRef mesh, const std::string& path);

	/**
	Saves a list of points as .ply file
	*/
	static void savePointsPly(const std::vector<ci::vec3>& points, const std::string& path);
};